# Generated by Django 4.1.1 on 2022-10-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preferences',
            new_name='Preference',
        ),
    ]
