# Generated by Django 4.1.1 on 2022-10-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_rename_preferences_preference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
        migrations.RenameModel(
            old_name='Thresholds',
            new_name='Threshold',
        ),
    ]
