# Generated by Django 4.1.1 on 2022-10-08 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_rename_news_new_rename_thresholds_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='news_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the news', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preference',
            name='preference_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for preference', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for profile', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for role', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for stock', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocks_list',
            name='stocks_list_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Stock List', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='threshold_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for threshold', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for User', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='watch_list',
            name='watchlist_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for watchlist', primary_key=True, serialize=False),
        ),
    ]
